### ISSUE TITLE
ALT + L binding on Mac prevents @

### ISSUE THREAD

**Issue by arigon** [BCJTI/vscode-multi-line-tricks#2]
The usage of this plugin on a Mac prevents the standard key binding for the @ symbol: ALT + L

**Comment by Bigous** [comment]
Hi @arigon , this plugin is not necessary anymore. It was incorporated by me on vscode itself and is part of the editor since [2016](https://github.com/microsoft/vscode/pull/1479).
It's on-line for study and back compatibility purposes only. Sorry about that :(
